# PowerShell script to import production backup data into development database
# This script is MANUAL ONLY - it will NOT run automatically
# Execute with: docker exec zaiken-postgres /backup-data/import-backup-0802.sh
# Or use this PowerShell script to execute the bash script inside the container
#
# NOTE: To add new tables, modify the IMPORT_ORDER array in import-backup-0802.sh
# See HOW_TO_ADD_TABLES.md for detailed instructions

$ErrorActionPreference = "Stop"

# Container name
$CONTAINER_NAME = "zaiken-postgres"

# Backup data directory (inside container)
$BACKUP_DIR = "/backup-data"

# Script name
$SCRIPT_NAME = "import-backup-0802.sh"

Write-Host "========================================" -ForegroundColor Green
Write-Host "Import Backup 0802 - Production to Dev" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host ""

# Check if container is running
Write-Host "Checking if container '$CONTAINER_NAME' is running..." -ForegroundColor Yellow
$containerStatus = docker ps --filter "name=$CONTAINER_NAME" --format "{{.Status}}"

if (-not $containerStatus) {
    Write-Host "ERROR: Container '$CONTAINER_NAME' is not running!" -ForegroundColor Red
    Write-Host "Please start the container with: docker-compose up -d" -ForegroundColor Yellow
    exit 1
}

Write-Host "[OK] Container is running" -ForegroundColor Green
Write-Host ""

# Check if script exists in container
Write-Host "Checking if script exists in container..." -ForegroundColor Yellow
$scriptExists = docker exec $CONTAINER_NAME test -f "$BACKUP_DIR/$SCRIPT_NAME"

if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Script not found in container at $BACKUP_DIR/$SCRIPT_NAME" -ForegroundColor Red
    Write-Host "Make sure:" -ForegroundColor Yellow
    Write-Host "  1. The volume is mounted correctly in docker-compose.yml" -ForegroundColor Yellow
    Write-Host "  2. The script file exists in the backup directory" -ForegroundColor Yellow
    Write-Host "  3. You have restarted the containers after modifying docker-compose.yml" -ForegroundColor Yellow
    exit 1
}

Write-Host "[OK] Script found" -ForegroundColor Green
Write-Host ""

# Make script executable (inside container)
Write-Host "Making script executable..." -ForegroundColor Yellow
docker exec $CONTAINER_NAME chmod +x "$BACKUP_DIR/$SCRIPT_NAME"

if ($LASTEXITCODE -ne 0) {
    Write-Host "WARNING: Could not make script executable, but continuing..." -ForegroundColor Yellow
}

Write-Host ""

# Confirm before proceeding
# Note: The list of tables is dynamically generated by the bash script
# To see the actual list, check the bash script's IMPORT_ORDER array
Write-Host "WARNING: This will DELETE all data from tables defined in the backup script" -ForegroundColor Yellow
Write-Host "And then import production data from backup." -ForegroundColor Yellow
Write-Host ""
Write-Host "Note: See import-backup-0802.sh for the complete list of tables." -ForegroundColor Cyan
Write-Host ""

$confirm = Read-Host "Do you want to continue? (yes/no)"

if ($confirm -ne "yes") {
    Write-Host "Import cancelled." -ForegroundColor Yellow
    exit 0
}

Write-Host ""
Write-Host "Executing import script inside container..." -ForegroundColor Green
Write-Host ""

# Execute the bash script inside the container
docker exec -it $CONTAINER_NAME "$BACKUP_DIR/$SCRIPT_NAME"

if ($LASTEXITCODE -eq 0) {
    Write-Host ""
    Write-Host "========================================" -ForegroundColor Green
    Write-Host "[OK] Import completed successfully!" -ForegroundColor Green
    Write-Host "========================================" -ForegroundColor Green
} else {
    Write-Host ""
    Write-Host "========================================" -ForegroundColor Red
    Write-Host "[ERROR] Import failed!" -ForegroundColor Red
    Write-Host "========================================" -ForegroundColor Red
    exit 1
}

